server:
  port: 8080
spring:
  application:
    name: "Usuarios"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/usuariosdb"
    username: "postgres"
    password: "1234"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
